export enum Routes {
	HOME = '/',
	LOGIN = '/login',
	DASHBOARD = '/dashboard',
	TIMELINE = '/timeline',
	PROFILE = '/profile',
	SETTINGS = '/settings',
	SETTINGS_SECTION = '/settings/:section',
	TRANSACTIONS = '/transactions',
	TRANSACTIONS_DETAIL = '/transactions/:transactionId',
	MERCHANTS = '/merchants',
	MERCHANTS_DETAIL = '/merchants/:merchantId',
	PEOPLE = '/people',
	PEOPLE_DETAIL = '/people/:personId',
	ACTIVITY = '/activity',
}
